### ISSUE TITLE
Duplicate utility functions in test utils

### ISSUE THREAD

**Issue by cafca** [p2panda/p2panda#293]
As an example, I noticed that there is a function `schema()` that returns a `SchemaId` given a schema id string in 

- test_utils/utils.rs
- test_utils/fixtures/params.rs

There's also a similar wrapper function in `test_utils/fixtures/defaults.rs`. I wondered whether we could restructure the `test_utils` module so that the code that generates values exists only in one easy to find place and if there's need for additional places to expose that functionality we create wrapper functions there?

There's more functions with the same pattern in these files.

**Comment by sandreae** [comment]
Thanks for flagging this, I also think this structure needs looking at. There were a few restrictions/needs which led to this design (not saying it ended up in the right place though :rofl:).

1) `rstest` `fixture` macro can define defaults which is a really nice pattern we use in the tests, however these defaults aren't available when the fixtures are used in the `rstest` `template` macros.... that's the main reason `test_utils/fixtures/defaults.rs` existed in the first place.
2) i wanted to access the mock node and client outside of just a test environment for building apps with memory storage (the playground), and am using common helper methods here. So this is why `test_utils/utils.rs` exists, the intention being that common helper methods would be defined here initially, then wrapped by the rstest fixture methods for use in tests.

Think there was another restriction which I can't remember now :-(

Aaaanyway, as I write this, I can see I was trying to do a "one tool for everything" job, which probably created a lot of these complications....

I think there might be a nice solution on the horizon though:

- the mock node can soon be deprecated, as we will have the memory traits and an in memory storage provider implementation. Which can be used both in tests, and also apps using p2panda. This removes the problem caused by 2.
- we could then probably find a much nicer structuring of the code and simple solution to 1.

Does that make sense? 

Defo up for finding a better structure in any case.
