### ISSUE TITLE
Provide document metadata on document view struct

### ISSUE THREAD

**Issue by cafca** [p2panda/p2panda#372]
Extend the `DocumentView` interface so that it also provides access to information that's available on `Document`.

- author
- schema
- `DocumentMeta`

**Comment by sandreae** [comment]
Thinks for raising this issue. We can for sure move things around wrt the `Document` and `DocumentView` structs. I'd like to follow through the thinking to make sure we have the right approach though.

The immediate reason for wanting to expand `DocumentView` is for the GraphQL client queries, here we want to be able to return meta data about a requested view (author, is_deleted, is_edited etc...). I want to check we are thinking about the long-term case here. For the short term we said we could interact with the store API to retrieve `DocumentView`s, but in the long term we would need a different interface. In which case, will we still be interacting with `DocumentView`s? I could imagine we would have some new `aquadoggo` query specific data types here, as it might not make sense to load up `DocumentView` with many things only related to our query implementation. In this case, it's not so important where this meta_data sits on our structs, as we can structure our db data as we need and compose queries that bring this together.

Next up I wonder where this meta_data is actually applied, if a document gets deleted for instance, does this piece of meta information apply to every view that exists for this document? Same for is_updated. I would say yes, as the observation is of the document rather than the view (as we discuss elsewhere, it may be up to nodes how to respond to this information, but that's a different discussion). I think it's worth thinking about what behaviour / meaning we expect to come across here, it might inform our thinking a little.

There are more spin-off questions from here, but maybe this is enough to get going.

Mainly I want to avoid changing things around as a knee-jerk reaction to our immediate need, then realising later on we just want to move things back, or that it wasn't necessary :rofl: I see we need access to the meta_data when answering queries, and that one solution is to move it all onto `DocumentView`s for sure.

**Comment by sandreae** [comment]
Other solutions for the short term problem:
- already introduce a wrapper struct in `aquadoggo` with all the meta_data our heart desires and compose queries which collect it all (using mostly what we already have in the db).
- instead of returning `DocumentView`s from the `DocumentStore` we return `Document`s

**Comment by adzialocha** [comment]
> Next up I wonder where this meta_data is actually applied, if a document gets deleted for instance, does this piece of meta information apply to every view that exists for this document? Same for is_updated. I would say yes, as the observation is of the document rather than the view (as we discuss elsewhere, it may be up to nodes how to respond to this information, but that's a different discussion). I think it's worth thinking about what behaviour / meaning we expect to come across here, it might inform our thinking a little.

Yes, I would assume the same here :+1:

> Other solutions for the short term problem

I like both solutions, they would not touch upon the actual `Document` and `DocumentView` types which I like for now. It could be too early to decide how we want to refactor our core data types?

**Comment by sandreae** [comment]
i would add to the possible solutions:

- already introduce a wrapper struct in aquadoggo with all the meta_data our heart desires _and also expand what is contained in the db tables for document_view to hold these values_.

**Comment by sandreae** [comment]
This isn't required anymore as we mainly handle documents (which contain requested metadata) instead of document views.
