### ISSUE TITLE
`SeqNum::skiplink_seq_num()` behaviour

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#417]
Here's the current behaviour:

```rust
pub fn skiplink_seq_num(&self) -> Option<Self> {
    Some(Self(lipmaa(self.0)))
}
```

Where `lipmaa()` always returns a lipmaa link (whether it is a duplicate of the backlink or not), and if the seq num is `1` then we get a skiplink of `0` which does not fit the p2panda spec. 

This behaviour seems strange to me, not sure why we are wrapping the result in an option, and of course the `0` value skiplink seq num is invalid.

**Comment by cafca** [comment]
I can see two meaningful behaviours here:

- always return `None` if no skiplink is required, because we don't need it. A malicious client could also encode _all_ entries with skiplinks and make processing them unnecessarily expensive for everyone who touches them.
- only return `None` for input seq num 1 where the resulting skiplink 0 is not a valid seq num
