### ISSUE TITLE
Introduce `Bytes` operation value

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#506]
`OperationValue::Bytes([u8])`

**Comment by sandreae** [comment]
This would be used in the `data` field of `blob_pieces_v1`.

**Comment by sandreae** [comment]
Thinking on this a little and realised we again have to deal with deserializing ambiguity. A `Bytes` value containing an empty vec would look the same as an empty `PinnedRelationList`. This is why `PlainOperation` has the `AmbiguousRelation` type which can only be typed when a schema is present.

**Comment by sandreae** [comment]
We can expand `AmbiguousRelation` to include bytes, renaming it to something like `AmbiguousVec`, or an alternative approach I thought of would be to specify that `Bytes` can't be empty... don't know if that's a strange solution though.

**Comment by adzialocha** [comment]
I would suspect CBOR encoding byte sequences differently than arrays (or almost anything else, really), but probably that doesn't work if your byte sequence is exactly a _CBOR encoded_ array? I assume you stumbled upon this because you used the cbor macros?

If that's not the case it's fine to go down the ambiguous route, we can't deserialize operations without a schema and maybe byte types are part of this.

**Comment by adzialocha** [comment]
I would suspect CBOR encoding byte sequences differently than arrays (or almost anything else, really), but probably that doesn't work if your byte sequence is exactly a _CBOR encoded_ array? I assume you stumbled upon this because you used the cbor macros?

If that's not the case it's fine to go down the ambiguous route, we can't deserialize operations without a schema and maybe byte types are part of this.

**Comment by sandreae** [comment]
Yeh, i tried with both `Vec<u8>` and `ByteBuf` from the `serde_bytes` crate (thin wrapper around the former which apparently encourages optimised byte encoding) and both got confused when serialising and then deserializing plain operations. Feels like there should be a way for bytes to be treaded differently from other arrays (even when empty), maybe I've just not found the trick yet.

**Comment by sandreae** [comment]
Update: when i specify that the vec should be treated as bytes (through serde macros) then `String` values are interpreted as `Bytes`. Still wrong, but in a different way. Progress? :rofl:

**Comment by sandreae** [comment]
Ok, so my suggestion is to replace the `StringOrRelation(String)` enum variant with `ByteString(&[u8])` which will be encoded as a cbor byte string value. As I understand it, cbor encodes strings and bytes in exactly the same way. 

This would mean string fields decode into bytes in `PlainValue` and so when we want to use them as strings we'll need and extra parsing step. 

This is the most elegant way of handling bytes and strings I can see though.

**Comment by sandreae** [comment]
Update: with the above change, there is still no way to differentiate between `ByteString` and `AmbiguousRelation` when the value is an empty array.
